google:
  oauth2:
    client:
      clientId: 472454960459-tmd9n592ddch2lt6mtrs34r1h4gfat5p.apps.googleusercontent.com
      clientSecret: TfNhlbeVgfLhNWj0RGvNkyRd
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      clientAuthenticationScheme: query
      scope: profile email
    resource:
      userInfoUri: https://www.googleapis.com/plus/v1/people/me
      preferTokenInfo: false