spring:
  profiles:
    active: dev

server:
  contextPath: /api


google:
    client:
      clientId: 36340005158-5oskfm6ojt1ak8ifd01uqagbemfrmmpc.apps.googleusercontent.com
      clientSecret: MRNmz3PtPjrn_18a2VnJs_1a
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      clientAuthenticationScheme: form
      scope: profile email openid
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
    api:
      key: AIzaSyBWDjzTHrBqOKiPdYWDX0XtnlcSofjmeNs

security:
   oauth2:
      client:
        client-id: default
        client-secret: 123456
        scope: read,write,trust
        auto-approve-scopes: '.*'

