spring:
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  contextPath: /api


google:
    client:
      clientId: 472454960459-tmd9n592ddch2lt6mtrs34r1h4gfat5p.apps.googleusercontent.com
      clientSecret: TfNhlbeVgfLhNWj0RGvNkyRd
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      clientAuthenticationScheme: form
      scope: profile email openid
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
    api:
      key: AIzaSyBWDjzTHrBqOKiPdYWDX0XtnlcSofjmeNs

security:
   oauth2:
      client:
        client-id: default
        client-secret: 123456
        scope: read,write,trust
        auto-approve-scopes: '.*'

